PUT http://localhost:3003/api/blogs/62d16279ec7ed2674c866fd6
Content-Type: application/json
Authorization: bearer

{
      "title": "How to always win at work life pt6",
      "author": "Jakki Heikkinen",
      "url": "http://123.com",
      "likes": 100
}
